#version: '3'
#services:
#  computer-01:
#    image: pycontribs/centos:7
#    container_name: clickhouse-01
#    restart: unless-stopped
#    entrypoint: "sleep infinity"
#  computer-02:
#    image: pycontribs/centos:7
#    container_name: vector-01
#    restart: unless-stopped
#    entrypoint: "sleep infinity"

version: '3.7'
services:
  app1:
    container_name: nginx
    image: "nginx"
    ports:
      - "80:80"
    restart: always
  app2:
    container_name: redis
    image: "redis"
    restart: always
